/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShrimpHeader {
        "variant": string;
    }
}
declare global {
    interface HTMLShrimpHeaderElement extends Components.ShrimpHeader, HTMLStencilElement {
    }
    var HTMLShrimpHeaderElement: {
        prototype: HTMLShrimpHeaderElement;
        new (): HTMLShrimpHeaderElement;
    };
    interface HTMLElementTagNameMap {
        "shrimp-header": HTMLShrimpHeaderElement;
    }
}
declare namespace LocalJSX {
    interface ShrimpHeader {
        "variant"?: string;
    }
    interface IntrinsicElements {
        "shrimp-header": ShrimpHeader;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shrimp-header": LocalJSX.ShrimpHeader & JSXBase.HTMLAttributes<HTMLShrimpHeaderElement>;
        }
    }
}
